ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER JAVADB IDENTIFIED BY 12345
  2  DEFAULT TABLESPACE USERS
  3  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO JAVADB;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER SCOTT IDENTIFIED BY TIGER
  2  DEFAULT TABLESPACE USERS
  3  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO SCOTT;